"""Existing configuration/ciphertext survive without active gateway code."""

from datetime import UTC, datetime

from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from alembic.util.exc import AutogenerateDiffsDetected
from anygarden.db.models import Base
from sqlalchemy import create_engine, insert, select

from .test_migrations import _alembic_config


def test_existing_gateway_rows_and_alembic_metadata_are_preserved(
    tmp_path, monkeypatch
):
    # Explicit scratch DB: even an inherited DB URL cannot select an operating DB.
    monkeypatch.delenv("ANYGARDEN_DB_URL", raising=False)
    path = tmp_path / "archive.db"
    cfg = _alembic_config(str(path))
    command.upgrade(cfg, "head")
    models = Base.metadata.tables["llm_gateway_models"]
    secrets = Base.metadata.tables["llm_gateway_secrets"]
    assert models.info["archived"] and secrets.info["archived"]
    from anygarden.mcp_templates.encryption import MCPSecrets
    from cryptography.fernet import Fernet

    cipher = MCPSecrets(Fernet.generate_key()).encrypt_dict({"key": "fixture-secret"})
    now = datetime.now(UTC)
    engine = create_engine(f"sqlite:///{path}")
    try:
        with engine.begin() as db:
            db.execute(
                insert(models).values(
                    id="old-model",
                    model_name="legacy",
                    provider="local",
                    upstream_model="old/model",
                    api_key_ref="OLD",
                    extra_params={"saved": True},
                    enabled=True,
                    created_at=now,
                    updated_at=now,
                )
            )
            db.execute(
                insert(secrets).values(
                    env_var_name="OLD",
                    encrypted_value=cipher,
                    last_tested_at=now,
                    last_test_status="ok",
                    created_at=now,
                    updated_at=now,
                )
            )
        # The actual environment's target_metadata is exercised by command.check.
        command.upgrade(cfg, "head")
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            # Existing unrelated FTS/nullability drift is outside this removal.
            # Check the actual env.py target_metadata has no archived-table diff.
            assert not any(
                name in repr(exc.diffs) for name in (models.name, secrets.name)
            )
        with engine.connect() as db:
            archived = {models.name, secrets.name}

            def include_object(obj, name, type_, reflected, compare_to):
                table_name = (
                    name
                    if type_ == "table"
                    else getattr(getattr(obj, "table", None), "name", None)
                )
                return table_name in archived

            context = MigrationContext.configure(
                db, opts={"include_object": include_object}
            )
            assert compare_metadata(context, Base.metadata) == []
            assert db.execute(select(models.c.extra_params)).scalar_one() == {
                "saved": True
            }
            assert db.execute(select(secrets.c.encrypted_value)).scalar_one() == cipher
        import anygarden.db.models as active_models

        assert not hasattr(active_models, "LLMGatewayModel")
        assert not hasattr(active_models, "LLMGatewaySecret")
    finally:
        engine.dispose()
